// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUhX2E0By8SVENql5mF4KvQR_uH6yPamQ',
    appId: '1:359439067832:web:0a1c53c690c50f6b4e224d',
    messagingSenderId: '359439067832',
    projectId: 'glorious-hope',
    authDomain: 'glorious-hope.firebaseapp.com',
    storageBucket: 'glorious-hope.firebasestorage.app',
    measurementId: 'G-TW7L2LGZW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACllx_r561xGlxeE6epqGQHdQQOZJLAt0',
    appId: '1:359439067832:android:2d91fa45cd0896d94e224d',
    messagingSenderId: '359439067832',
    projectId: 'glorious-hope',
    storageBucket: 'glorious-hope.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwxEC5rF_hyrbGeOgBIq6dbxrJ-zQlrPs',
    appId: '1:359439067832:ios:57d751729e2123d24e224d',
    messagingSenderId: '359439067832',
    projectId: 'glorious-hope',
    storageBucket: 'glorious-hope.firebasestorage.app',
    iosBundleId: 'com.example.redebugger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwxEC5rF_hyrbGeOgBIq6dbxrJ-zQlrPs',
    appId: '1:359439067832:ios:57d751729e2123d24e224d',
    messagingSenderId: '359439067832',
    projectId: 'glorious-hope',
    storageBucket: 'glorious-hope.firebasestorage.app',
    iosBundleId: 'com.example.redebugger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUhX2E0By8SVENql5mF4KvQR_uH6yPamQ',
    appId: '1:359439067832:web:b32119845be32be44e224d',
    messagingSenderId: '359439067832',
    projectId: 'glorious-hope',
    authDomain: 'glorious-hope.firebaseapp.com',
    storageBucket: 'glorious-hope.firebasestorage.app',
    measurementId: 'G-D2YR2TMT96',
  );

}